language: scala

jdk:
  - openjdk8
  - openjdk11

node_js: 9

script:
  ## This runs the template with the default parameters, and runs test within the templated app.
  - sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M test

cache:
  yarn: true
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers

before_cache:
# Cleanup the cached directories to avoid unnecessary cache updates
- find $HOME/.ivy2       -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete

notifications:
  webhooks:
    if: branch = master
    urls:
      - https://webhooks.gitter.im/e/07b9efe2db0a76c2816c
    on_success: change
    on_failure: always
    on_start: never
